---
roundcube_docker_purge_all: false
roundcube_docker_image: "roundcube/roundcubemail:latest"
roundcube_db_type: "mysql"
roundcube_db_name: "roundcubemail"
roundcube_db_user: "roundcube"
roundcube_db_password: "CHANGE_ME_ROUNDCUBE_DB_PASSWORD"
roundcube_des_key: "rcmail-2026-dynamic-stack-secret"
roundcube_expose_port: 80
roundcube_imap_port: 993
roundcube_smtp_port: 465
roundcube_skin: "elastic"
roundcube_imap_cluster: "{{ groups['dovecot_servers'] | map('extract', hostvars,
  ['ansible_host']) | list }}"
roundcube_smtp_cluster: "{{ groups['postfix_servers'] | map('extract', hostvars,
  ['ansible_host']) | list }}"

roundcube_plugins:
  - archive
  - zipdownload
  #- managesieve
  - password
  - markasjunk
  - identity_select
  - help
  - emoticons
  - attachment_reminder
  - vcard_attachments
  - identicon
  - enigma
  - show_additional_headers

