---
- name: restart unbound
  ansible.builtin.systemd:
    name: unbound
    state: restarted
    daemon_reload: yes

- name: reload unbound
  ansible.builtin.systemd:
    name: unbound
    state: reloaded