---
- name: reload haproxy
  ansible.builtin.systemd:
    name: haproxy
    state: reloaded  # Graceful reload - zero downtime
    daemon_reload: yes

- name: restart rsyslog
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

    